name: Node.js CI

on:
  push:
    branches: [ "github-actions" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies and run the app
      run: yarn

    - name: Monitor webpack serve output
      run: |
        while [[ $? -ne 0 ]]; do
          npm run start-dev 2>&1 | tail -n 1
          if [[ $? -eq 0 ]]; then
            echo "Webpack compiled successfully"
            break
          fi
          sleep 1
        done

    - name: Sleep for 5 seconds
      run: sleep 5

    - name: Exit
      run: exit 0
