name: Node.js CI

on:
  push:
    branches: [ "github-actions" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-app

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies and run the app
      run: yarn && yarn start

    - name: Wait for yarn start to finish
      run: watch -n 1 'yarn start' | grep -q 'exited 0'

    - name: Sleep for 5 seconds
      run: sleep 5

    - name: Exit
      run: exit 0